// Generated by CoffeeScript 1.7.1
(function() {
  exports.page = function(_arg) {
    var bundle, groupName, list, listHtml, todo, _ref;
    _ref = _arg != null ? _arg : {}, groupName = _ref.groupName, list = _ref.list, bundle = _ref.bundle;
    listHtml = ((function() {
      var _i, _len, _ref1, _results;
      _ref1 = list || [];
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        todo = _ref1[_i];
        _results.push(exports.todo(todo));
      }
      return _results;
    })()).join('');
    bundle = JSON.stringify(bundle).replace(/'/g, '&#39;');
    return "<!DOCTYPE html>\n<meta charset=\"utf-8\">\n<title>Racer todos - " + groupName + "</title>\n<link rel=\"stylesheet\" href=\"style.css\">\n<form id=\"head\" onsubmit=\"return false\">\n  <h1>Todos</h1>\n  <div id=\"add\">\n    <div id=\"add-input\"><input id=\"new-todo\"></div>\n    <input id=\"add-button\" type=\"submit\" value=\"Add\">\n  </div>\n</form>\n<div id=\"dragbox\"></div>\n<form id=\"content\" autocomplete=\"off\">\n  <ul id=\"list\">" + listHtml + "</ul>\n</form>\n<script async src=\"/script.js\" data-bundle='" + bundle + "'></script>";
  };

  exports.todo = function(todo) {
    var checked, completed, text;
    if (!todo) {
      return '<li style="display:none"></li>';
    }
    if (todo.completed) {
      completed = 'completed';
      checked = 'checked';
    } else {
      completed = '';
      checked = '';
    }
    text = (todo.text || '').replace(/"/g, '&quot;');
    return "<li id=\"" + todo.id + "\" class=\"" + completed + "\">\n  <table width=\"100%\">\n    <td class=\"handle\" width=\"0\"></td>\n    <td width=\"100%\">\n      <div class=\"todo\">\n        <label><input type=\"checkbox\" " + checked + "><i></i></label>\n        <input class=\"text\" value=\"" + text + "\"><i></i>\n      </div>\n    </td>\n    <td width=\"0\"><button type=\"button\" class=\"delete\">Delete</button></td>\n  </table>\n</li>";
  };

}).call(this);
